"""
    Traject Data • SERP Data API

    Traject Data • trajectdata.com • SERP Data API • SERP Data API for Scale | Locale SEO | Agencies | Brands  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Contact: support@trajectdata.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import traject_data
from traject_data.model.error import Error


class TestError(unittest.TestCase):
    """Error unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testError(self):
        """Test Error"""
        # FIXME: construct object with mandatory attributes with example values
        # model = Error()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
