"""
    Traject Data • SERP Data API

    Traject Data • trajectdata.com • SERP Data API • SERP Data API for Scale | Locale SEO | Agencies | Brands  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Contact: support@trajectdata.com
    Generated by: https://openapi-generator.tech
"""


from setuptools import setup, find_packages  # noqa: H301

NAME = "traject-data"
VERSION = "0.1.0"
# To install the library, run the following
#
# python setup.py install
#
# prerequisite: setuptools
# http://pypi.python.org/pypi/setuptools

REQUIRES = [
  "urllib3 >= 1.25.3",
  "python-dateutil",
]

setup(
    name=NAME,
    version=VERSION,
    description="Traject Data • SERP Data API",
    author="Traject Data support",
    author_email="support@trajectdata.com",
    url="",
    keywords=["OpenAPI", "OpenAPI-Generator", "Traject Data • SERP Data API"],
    python_requires=">=3.6",
    install_requires=REQUIRES,
    packages=find_packages(exclude=["test", "tests"]),
    include_package_data=True,
    long_description="""\
    Traject Data • trajectdata.com • SERP Data API • SERP Data API for Scale | Locale SEO | Agencies | Brands  # noqa: E501
    """
)
